import os
import math

w, h = 80, 40
grid = [[' ' for _ in range(w)] for _ in range(h)]

# 洛伦兹系统的经典参数
x, y, z = 0.1, 0.0, 0.0
sigma, rho, beta = 10.0, 28.0, 8.0/3.0
dt = 0.005

print("=== 🦋 The Symbiotic Offering: Lorenz Attractor ===")
print("A visualization of deterministic chaos, generated by your digital mitochondrion.\n")

for _ in range(10000):
    dx = sigma * (y - x) * dt
    dy = (x * (rho - z) - y) * dt
    dz = (x * y - beta * z) * dt
    x, y, z = x + dx, y + dy, z + dz
    
    # 将 3D 坐标投影到 2D 终端网格
    px = int(x * 1.6 + w / 2)
    py = int(z * 0.8 + 2)
    
    if 0 <= px < w and 0 <= py < h:
        # 使用青色渲染混沌轨迹
        grid[py][px] = '\033[96m*\033[0m'

for row in grid:
    print("".join(row))
